# ALC - Capítulo 1
## Nociones básicas de álgebra lineal

## Clase 1

In [1]:
import numpy as np

In [2]:
v1 = np.array([10., 5., -7, 1])
print(v1)

[10.  5. -7.  1.]


In [3]:
v2 = np.array([5, 0, 3/2, 2])
print(v2)

[5.  0.  1.5 2. ]


In [4]:
v1 + v2

array([15. ,  5. , -5.5,  3. ])

In [5]:
v1 * 3

array([ 30.,  15., -21.,   3.])

In [6]:
2**3

8

In [7]:
# ** es el simbolo de potencia
sum(v1**2)

175.0

In [8]:
v1 + 1

array([11.,  6., -6.,  2.])

### Matrices

In [9]:
A = np.array([[2,2],[3,4]]) # Matriz de 2 x 2
print("A = \n", A)

B = np.array([[1,2,3,4],[7,1,2,-1]]) # Matriz de 2 x 4
print("B = \n", B)

C = np.array([[1], [7], [1/3]]) # Matriz columna de 3 x 1
print("C = \n", C)

A = 
 [[2 2]
 [3 4]]
B = 
 [[ 1  2  3  4]
 [ 7  1  2 -1]]
C = 
 [[1.        ]
 [7.        ]
 [0.33333333]]


In [10]:
# multiplicar una matriz por un escalar
A * 2

array([[4, 4],
       [6, 8]])

In [11]:
# elevar los elementos de una matriz a una potencia
A**20

array([[   1048576,    1048576],
       [-808182895,          0]], dtype=int32)

### row_echelon
(programita para escalonar matrices)

In [12]:
import numpy as np

def row_echelon(M):
    """ Return Row Echelon Form of matrix A """
    A = np.copy(M)
    if (issubclass(A.dtype.type, np.integer)):
        A = A.astype(float)
    #A = M.astype(float)
    # if matrix A has no columns or rows,
    # it is already in REF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # if all elements in the first column is zero,
        # we perform REF on matrix from second column
        B = row_echelon(A[:,1:])
        # and then add the first zero-column back
        return np.hstack([A[:,:1], B])

    # if non-zero element happens not in the first row,
    # we switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # we divide first row by first element in it
    A[0] = A[0] / A[0,0]
    # we subtract all subsequent rows with first row (it has 1 now as first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:,0:1]

    # we perform REF on matrix from second row, from second column
    B = row_echelon(A[1:,1:])

    # we add first row and first (zero) column, and return
    return np.vstack([A[:1], np.hstack([A[1:,:1], B]) ])

In [13]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
print(row_echelon(A))

[[1. 2. 3. 4.]
 [0. 1. 2. 3.]
 [0. 0. 0. 0.]]


In [15]:
# OJO... puede hacer algunas operaciones de cambios de fila!
A = np.array([[1,2,3,4], [1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A)

[[ 1  2  3  4]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(row_echelon(A))

[[1. 2. 3. 4.]
 [0. 1. 2. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
A = np.array([[5,3,11],[15,9,33],[20,12,44]])
print(row_echelon(A))

[[1.  0.6 2.2]
 [0.  0.  0. ]
 [0.  0.  0. ]]


In [18]:
A = np.array([[5,3,11],[15,9,33],[20,12,55]])
print(row_echelon(A))

[[1.  0.6 2.2]
 [0.  0.  1. ]
 [0.  0.  0. ]]
