In [10]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as scp


In [11]:
#Ejercicio 1
def descompLU (A):
  n = A.shape[0] # Sacamos el n de la matriz
  if np.linalg.det(A)==0:
    I=np.eye(n)
    return I,A
  else:
    if n==1:
      I=np.eye(1)
      return I, A
    else:
      if A[0,0]==0:
        return np.eye(n),A
      else:
        A11=A[0,0]
        A12=A[0,1:]
        A21=A[1:,0]
        A22=A[1:, 1:]
        L=np.zeros([n,n])
        U=np.zeros([n,n])
        L21=A21/A11
        L[1:,0] = L21
        U12=A12
        resta = L21.reshape(-1, 1) @ U12.reshape(1, -1)
        LU=A22-resta
        Ele, uu=descompLU(LU)
        L[0,0]=1
        L[1:,1:]=Ele
        U[0,0]=A11
        U[0,1:]=A12
        U[1:,1:]=uu
        for i in range(n):
          if L[i,i]==0 or U[i,i]==0:
            return np.eye(n),A
        return L,U

In [78]:
def solve_Ly(A,b):
    res=[]
    res.append(b[0]/A[0,0])
    for i in range(1,len(A)):
        r=0
        for j in range(i):
            r=r+A[i,j]*res[j]
        sol=(b[i]-r)
        res.append(sol)

    return y


def solve_Ux(U, y):
    n = len(U)
    res = []
    res.append(y[n - 1] / U[n - 1, n - 1])
    i = n - 2
    while i >= 0:
        k = 0
        r = 0
        j = n - 1
        while j > i:
            r = r + U[i, j] * res[k]
            j = j - 1
            k=k+1
        sol = (y[i] - r) / U[i, i]
        res.append(sol)
        i = i - 1

    x = np.zeros(n)
    for i in range(n):
        x[i] = np.take(res,len(res)-1-i) #res.pop()
    return x

# Ejemplo de uso
U = np.array([[1.0, -1.0, 0.0, 1.0], [0.0, 1.0, 4.0, 0.0], [0.0, 0.0, -4.0, -4.0], [0.0, 0.0, 0.0, 2.0]])
y = np.array([1.0, -7.0, 0.0, 4.0])
x = solve_Ux(U, y)
print(x)



[ 0.  1. -2.  2.]


In [79]:
from scipy.linalg import solve_triangular as st
A=np.array([[1,-1,0,1],[0,1,4,0],[2,-1,0,-2],[-3,3,0,-1]])
L,U=descompLU(A)
b=np.array([[1,-7,-5,1]]).T
y=np.array([[1,-7,0,4]]).T
ej3=solve_Ly(L,b)
ej3b=solve_Ux(U,ej3)
print("Ya creada", st(L,b, lower=True))
print("La mia: ", ej3)

print("Ya creada", st(U,y))
print("La mia: ", ej3b)


Ya creada [[ 1.]
 [-7.]
 [ 0.]
 [ 4.]]
La mia:  [[ 1]
 [-7]
 [ 0]
 [ 4]]
Ya creada [[ 0.]
 [ 1.]
 [-2.]
 [ 2.]]
La mia:  [ 0.  1. -2.  2.]


In [27]:
h=solve_Ly(L,b)
h

array([[ 1],
       [-7],
       [ 0],
       [ 4]])

In [81]:
def resolverLU(A, b):
    L, U = descompLU(A)
    y=solve_Ly(L,b)
    x = solve_Ux(U,y)
    return x

In [82]:
A = np.array([[1, -1, 0, 1], [0, 1, 4, 0], [2, -1, 0, -2], [-3, 3, 0, -1]])
b = np.array([[1, -7, -5, 1]]).T
resolverLU(A, b)

array([ 0.,  1., -2.,  2.])