Álgebra Lineal Computacional
TP 1

Integrantes:
    Joel LU
    Martín Menalled LU 339/22



In [1]:
import numpy as np  # Importamos librería

In [9]:
#Ejercicio 1
def descompLU (A):
  n = A.shape[0] # Sacamos el n de la matriz
  if np.linalg.det(A)==0:
    I=np.eye(n)
    return I,A
  else:
    if n==1:
      I=np.eye(1)
      return I, A
    else:
      if A[0,0]==0:
        return np.eye(n),A
      else:
        A11=A[0,0]
        A12=A[0,1:]
        A21=A[1:,0]
        A22=A[1:, 1:]
        L=np.zeros([n,n])
        U=np.zeros([n,n])
        L21=A21/A11
        L[1:,0] = L21
        U12=A12
        resta = L21.reshape(-1, 1) @ U12.reshape(1, -1)
        LU=A22-resta
        Ele, uu=descompLU(LU)
        L[0,0]=1
        L[1:,1:]=Ele
        U[0,0]=A11
        U[0,1:]=A12
        U[1:,1:]=uu
        for i in range(n):
          if L[i,i]==0 or U[i,i]==0:
            return np.eye(n),A
        return L,U

In [3]:
C=np.array([[3]])
B=np.array([[5,2],[3,5]])
A = np.array([[2, -3, 5], [6, -1, 3], [-4, 1, -2]])
D = np.array([[1,1,1],[1,1,2],[1,3,5]])

descompLU(D)


(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1, 1, 1],
        [1, 1, 2],
        [1, 3, 5]]))

In [4]:
import numpy as np
import math
import traceback


def mntest(func):
    global tests

    tests.append(func)

    return func

def correr_tests():
    excepciones = []
    for test in tests:
        try:
            print("Corriendo {} ... ".format(test.__name__), end='')
            test()
            print("OK")
        except AssertionError as e:
            error_msg = traceback.format_exc()
            excepciones.append((test, error_msg))
            print("ERROR")

    if len(excepciones) > 0:
        print("\nErrores:\n")
        for (test, error_msg) in excepciones:
            print("En {}".format(test.__name__))
            print(error_msg)
    else:
        print("\n\nTodos los tests pasaron correctamente")

In [5]:
tests = []


@mntest
def testear_con_multiplo_identidad():
    A = 3 * np.identity(3)

    L, U = descompLU(A)

    assert(np.allclose(L, np.eye(3)))
    assert(np.allclose(U, 3*np.eye(3)))



@mntest
def testear_con_otra_matriz():
    L = np.array([
        [1, 0, 0],
        [1, 1, 0],
        [1, 1, 1],
    ])

    U = np.array([
        [1, 1, 1],
        [0, 2, 2],
        [0, 0, 3],
    ])

    A = L @ U

    L1, U1 = descompLU(A)

    assert(np.allclose(L1, L))
    assert(np.allclose(U1, U))

@mntest
def testear_con_otra_matriz2():
    A = np.array([
        [8, 2, 0],
        [4, 9, 4],
        [6, 7, 9],
    ])



    L1, U1 = descompLU(A)

    assert(np.allclose(L1@U1, A))



correr_tests()

Corriendo testear_con_multiplo_identidad ... OK
Corriendo testear_con_otra_matriz ... OK
Corriendo testear_con_otra_matriz2 ... OK


Todos los tests pasaron correctamente


In [6]:
A=np.array([[1,-1,0,1],[0,1,4,0],[2,-1,0,-2],[-3,3,0,-1]])
L,U=descompLU(A)
b=np.array([[1,-7,-5,1]]).T
y=np.array([[1,-7,0,4]]).T
np.linalg.solve(L,b)
np.linalg.solve(U,y)

array([[ 0.],
       [ 1.],
       [-2.],
       [ 2.]])

In [7]:
from scipy.linalg import solve_triangular as st
def resolverLU(A,b):
    L,U=descompLU(A)
    y=st(L,b, lower=True)
    x=st(U,y)
    return x


In [8]:
A=np.array([[1,-1,0,1],[0,1,4,0],[2,-1,0,-2],[-3,3,0,-1]])
b=np.array([[1,-7,-5,1]]).T
resolverLU(A,b)

array([[ 0.],
       [ 1.],
       [-2.],
       [ 2.]])